### ISSUE TITLE
Add Builder-Method to configure Uppercase Names

### ISSUE THREAD

**Issue by MaZderMind** [igorspasic/nomen-est-omen#3]
To Discriminate between, let's say, a Key and a Display-Value it would be nice to be able to generate Uppercase Names:

```
Nomen.est().casing(Casing.WORD).separator(" ").color().adjective().person()
 = "Green Hopeful Meninsky"
```

This could be used together with a Library like Gihub's Slugify to generate a Slugified key to the more Display-Like name.

**Comment by igr** [comment]
Done! Please check the code, let me know if this is OK :)

Thanx for the idea!
